### ISSUE TITLE
Doesn't work on the latest Chrome.

### ISSUE THREAD

**Issue by meetconverge** [CSWilson/Viewport-Dimensions#7]
The dimensions don't seem to work on the latest Chrome. Version 40.0.2214.115 (64-bit) on Mac OSX Yosemite.

**Comment by CSWilson** [comment]
Thanks for the feedback, It seems to be working for me on OS X 10.10.2 running Chrome 40.0.2214.115 (64-bit) It only shows when you resize your browser, also you may try disabling the plugin then reenabling it, you may also try restarting your system after installing it.
![screen shot 2015-03-01 at 9 38 10 pm](https://cloud.githubusercontent.com/assets/2521396/6435451/a5c616bc-c05b-11e4-8079-6221f5c083ed.png)

**Comment by meetconverge** [comment]
Disabling and enabling the plugin worked. I should have tried that before posting the issue. Sorry for all the trouble. Fantastic work on the extension. Thanks for developing this. :)
